# Customer data creation on Olist Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import gdown

import warnings
warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8-pastel')

### Importing all the datasets

In [2]:
data=pd.read_csv(r"C:\Users\Rano's PC\Machine\github_repo_cloned\Elevvo_Internship\Task-9\order level data.csv")

In [3]:
id="1G2oYtiemP-24kPm2Zds_u98Qv0dzvtmP"
gdown.download(f"https://drive.google.com/uc?id={id}", "order_reviews.csv", quiet=False)

order_reviews=pd.read_csv('order_reviews.csv')

Downloading...
From: https://drive.google.com/uc?id=1G2oYtiemP-24kPm2Zds_u98Qv0dzvtmP
To: C:\Users\Rano's PC\Machine\order_reviews.csv
100%|█████████████████████████████████████████████████████████████████████████████| 14.5M/14.5M [00:01<00:00, 10.0MB/s]

In [4]:
data.head()

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,...,payment_value,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,...,38.71,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,...,141.46,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,...,179.12,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,...,72.20,3.0,450.0,30.0,10.0,20.0,31842.0,belo horizonte,MG,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,...,28.62,4.0,250.0,51.0,15.0,15.0,8752.0,mogi das cruzes,SP,stationery

In [5]:
data.columns

Index(['order_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'price', 'seller_id',
       'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'product_photos_qty',
       'product_weight_g', 'product_length_cm', 'product_height_cm',
       'product_width_cm', 'seller_zip_code_prefix', 'seller_city',
       'seller_state', 'product_category_name_english'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   order_status                   99441 non-null  object
 2   order_purchase_timestamp       99441 non-null  object
 3   order_approved_at              99281 non-null  object
 4   order_delivered_carrier_date   97658 non-null  object
 5   order_delivered_customer_date  96476 non-null  object
 6   order_estimated_delivery_date  99441 non-null  object
 7   customer_unique_id             99441 non-null  object
 8   customer_zip_code_prefix       99441 non-null  int64
 9   customer_city                  99441 non-null  object
 10  customer_state                 99441 non-null  object
 11  order_item_id                  98666 non-null  float64
 12  product_id                     98666 non-null  object
 13  price                          98666 non-null  float64
 14  seller_id                      98666 non-null  object
 15  freight_value                  98666 non-null  float64
 16  payment_sequential             99440 non-null  float64
 17  payment_type                   99440 non-null  object
 18  payment_installments           99440 non-null  float64
 19  payment_value                  99440 non-null  float64
 20  product_photos_qty             97248 non-null  float64
 21  product_weight_g               98650 non-null  float64
 22  product_length_cm              98650 non-null  float64
 23  product_height_cm              98650 non-null  float64
 24  product_width_cm               98650 non-null  float64
 25  seller_zip_code_prefix         98666 non-null  float64
 26  seller_city                    98666 non-null  object
 27  seller_state                   98666 non-null  object
 28  product_category_name_english  97226 non-null  object
dtypes: float64(12), int64(1), object(16)
memory usage: 22.0+ MB

In [7]:
data['order_approved_at']=pd.to_datetime(data['order_approved_at'])

In [8]:
data['order_delivered_carrier_date']=pd.to_datetime(data['order_delivered_carrier_date'])

In [9]:
data['order_purchase_timestamp']=pd.to_datetime(data['order_purchase_timestamp'])

In [10]:
data['order_delivered_customer_date']=pd.to_datetime(data['order_delivered_customer_date'])

In [11]:
data['order_estimated_delivery_date']=pd.to_datetime(data['order_estimated_delivery_date'])

In [12]:
data.rename(columns={'order_status':'status','order_purchase_timestamp':'purchase_date','order_approved_at':'approve_date','order_delivered_carrier_date':'delivered_carrier_date',
                     'order_delivered_customer_date':'delivered_customer_date','order_estimated_delivery_date':'estimated_delivery_date','customer_unique_id':'customer_id',
                     'customer_zip_code_prefix':'customer_zip','seller_zip_code_prefix':'seller_zip','product_category_name_english':'product_category'},inplace=True)

In [13]:
cols=['customer_zip','seller_zip']
data[cols]=data[cols].astype(str)

In [14]:
def hour_classification(hour):
    if 5 <= hour < 8:
        return 'early morning'
    elif 8 <= hour < 12:
        return 'morning'
    elif 12 <= hour < 16:
        return 'afternoon'
    elif 16 <= hour < 20:
        return 'evening'
    elif 20 <= hour < 24:
        return 'night'
    else:  # 0 <= hour < 5
        return 'midnight'

In [15]:
data['purchase_time']=data['purchase_date'].dt.hour.apply(hour_classification)

In [16]:
data['purchase_date']=pd.to_datetime(data['purchase_date'].dt.date)

In [17]:
data['approve_time']=data['approve_date'].dt.hour.apply(hour_classification)

In [18]:
data['approve_date']=pd.to_datetime(data['approve_date'].dt.date)

In [19]:
data['delivered_carrier_time']=data['delivered_carrier_date'].dt.hour.apply(hour_classification)

In [20]:
data['delivered_carrier_date']=pd.to_datetime(data['delivered_carrier_date'].dt.date)

In [21]:
data['delivered_customer_time']=data['delivered_customer_date'].dt.hour.apply(hour_classification)

In [22]:
data['delivered_customer_date']=pd.to_datetime(data['delivered_customer_date'].dt.date)

In [23]:
data.drop(columns=['product_photos_qty', 'product_length_cm',
       'product_height_cm', 'product_width_cm'],inplace=True)

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 99441 non-null  object
 1   status                   99441 non-null  object
 2   purchase_date            99441 non-null  datetime64[ns]
 3   approve_date             99281 non-null  datetime64[ns]
 4   delivered_carrier_date   97658 non-null  datetime64[ns]
 5   delivered_customer_date  96476 non-null  datetime64[ns]
 6   estimated_delivery_date  99441 non-null  datetime64[ns]
 7   customer_id              99441 non-null  object
 8   customer_zip             99441 non-null  object
 9   customer_city            99441 non-null  object
 10  customer_state           99441 non-null  object
 11  order_item_id            98666 non-null  float64
 12  product_id               98666 non-null  object
 13  price                    98666 non-null  float64
 14  seller_id                98666 non-null  object
 15  freight_value            98666 non-null  float64
 16  payment_sequential       99440 non-null  float64
 17  payment_type             99440 non-null  object
 18  payment_installments     99440 non-null  float64
 19  payment_value            99440 non-null  float64
 20  product_weight_g         98650 non-null  float64
 21  seller_zip               99441 non-null  object
 22  seller_city              98666 non-null  object
 23  seller_state             98666 non-null  object
 24  product_category         97226 non-null  object
 25  purchase_time            99441 non-null  object
 26  approve_time             99441 non-null  object
 27  delivered_carrier_time   99441 non-null  object
 28  delivered_customer_time  99441 non-null  object
dtypes: datetime64[ns](5), float64(7), object(17)
memory usage: 22.0+ MB

In [25]:
data['delivery_days']=(data['delivered_customer_date']-data['purchase_date']).dt.days

In [27]:
data['used_installments']=data['payment_installments'].apply(lambda x: 1 if x>1 else 0)

In [29]:
data['used_sequential']=data['payment_sequential'].apply(lambda x: 1 if x>1 else 0)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 99441 non-null  object
 1   status                   99441 non-null  object
 2   purchase_date            99441 non-null  datetime64[ns]
 3   approve_date             99281 non-null  datetime64[ns]
 4   delivered_carrier_date   97658 non-null  datetime64[ns]
 5   delivered_customer_date  96476 non-null  datetime64[ns]
 6   estimated_delivery_date  99441 non-null  datetime64[ns]
 7   customer_id              99441 non-null  object
 8   customer_zip             99441 non-null  object
 9   customer_city            99441 non-null  object
 10  customer_state           99441 non-null  object
 11  order_item_id            98666 non-null  float64
 12  product_id               98666 non-null  object
 13  price                    98666 non-null  float64
 14  seller_id                98666 non-null  object
 15  freight_value            98666 non-null  float64
 16  payment_sequential       99440 non-null  float64
 17  payment_type             99440 non-null  object
 18  payment_installments     99440 non-null  float64
 19  payment_value            99440 non-null  float64
 20  product_weight_g         98650 non-null  float64
 21  seller_zip               99441 non-null  object
 22  seller_city              98666 non-null  object
 23  seller_state             98666 non-null  object
 24  product_category         97226 non-null  object
 25  purchase_time            99441 non-null  object
 26  approve_time             99441 non-null  object
 27  delivered_carrier_time   99441 non-null  object
 28  delivered_customer_time  99441 non-null  object
 29  delivery_days            96476 non-null  float64
 30  used_installments        99441 non-null  int64
 31  used_sequential          99441 non-null  int64
dtypes: datetime64[ns](5), float64(8), int64(2), object(17)
memory usage: 24.3+ MB

In [31]:
data.columns

Index(['order_id', 'status', 'purchase_date', 'approve_date',
       'delivered_carrier_date', 'delivered_customer_date',
       'estimated_delivery_date', 'customer_id', 'customer_zip',
       'customer_city', 'customer_state', 'order_item_id', 'product_id',
       'price', 'seller_id', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value',
       'product_weight_g', 'seller_zip', 'seller_city', 'seller_state',
       'product_category', 'purchase_time', 'approve_time',
       'delivered_carrier_time', 'delivered_customer_time', 'delivery_days',
       'used_installments', 'used_sequential'],
      dtype='object')

In [35]:
def cancel_rate(x):
    return (x == 'canceled').sum() / x.nunique()


def safe_mode(x):
    m = x.mode()
    return m.iloc[0] if not m.empty else None

customer_data=data.groupby('customer_id').agg({
        'status': cancel_rate,
        'purchase_date': 'min',
        'customer_city': 'first',
        'customer_state': 'first',
        'customer_zip': 'first',
        'order_item_id': 'count',
        'price': ['sum', 'mean'],
        'freight_value': ['sum', 'mean'],
        'payment_type': safe_mode,
        'product_weight_g': 'median',
        'seller_id': safe_mode,
        'seller_city': safe_mode,
        'seller_state': safe_mode,
        'product_category': safe_mode,
        'purchase_time': safe_mode,
        'delivery_days': 'mean',
        'used_installments': lambda x: int((x > 0).any()),
        'used_sequential': lambda x: int((x > 0).any())
    }).reset_index()

In [36]:
customer_data.columns = ['_'.join(col).strip('_') for col in customer_data.columns.values]

In [37]:
customer_data.head()

,customer_id,status_cancel_rate,purchase_date_min,customer_city_first,customer_state_first,customer_zip_first,order_item_id_count,price_sum,price_mean,freight_value_sum,...,payment_type_safe_mode,product_weight_g_median,seller_id_safe_mode,seller_city_safe_mode,seller_state_safe_mode,product_category_safe_mode,purchase_time_safe_mode,delivery_days_mean,used_installments_<lambda>,used_sequential_<lambda>
0,0000366f3b9a7992bf8c76cfdf3221e2,0.0,2018-05-10,cajamar,SP,7787,1,129.90,129.90,12.00,...,credit_card,1500.0,da8622b14eb17ae2831f4ac5b9dab84a,piracicaba,SP,bed_bath_table,morning,6.0,1,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,0.0,2018-05-07,osasco,SP,6053,1,18.90,18.90,8.29,...,credit_card,375.0,138dbe45fc62f1e244378131a6801526,sao paulo,SP,health_beauty,morning,3.0,0,0
2,0000f46a3911fa3c0805444483337064,0.0,2017-03-10,sao jose,SC,88115,1,69.00,69.00,17.22,...,credit_card,1500.0,3d871de0142ce09b7081e2b9d1733cb1,campo limpo paulista,SP,stationery,night,26.0,1,0
3,0000f6ccb0745a6a4b88665a16c9f078,0.0,2017-10-12,belem,PA,66812,1,25.99,25.99,17.63,...,credit_card,150.0,ef506c96320abeedfb894c34db06f478,sao paulo,SP,telephony,night,20.0,1,0
4,0004aac84e0df4da2b147fca70cf8255,0.0,2017-11-14,sorocaba,SP,18040,1,180.00,180.00,16.89,...,credit_card,6050.0,70a12e78e608ac31179aea7f8422044b,jacarei,SP,telephony,evening,13.0,1,0

In [38]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96096 entries, 0 to 96095
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 96096 non-null  object
 1   status_cancel_rate          96096 non-null  float64
 2   purchase_date_min           96096 non-null  datetime64[ns]
 3   customer_city_first         96096 non-null  object
 4   customer_state_first        96096 non-null  object
 5   customer_zip_first          96096 non-null  object
 6   order_item_id_count         96096 non-null  int64
 7   price_sum                   96096 non-null  float64
 8   price_mean                  95420 non-null  float64
 9   freight_value_sum           96096 non-null  float64
 10  freight_value_mean          95420 non-null  float64
 11  payment_type_safe_mode      96095 non-null  object
 12  product_weight_g_median     95407 non-null  float64
 13  seller_id_safe_mode         95420 non-null  object
 14  seller_city_safe_mode       95420 non-null  object
 15  seller_state_safe_mode      95420 non-null  object
 16  product_category_safe_mode  94060 non-null  object
 17  purchase_time_safe_mode     96096 non-null  object
 18  delivery_days_mean          93356 non-null  float64
 19  used_installments_<lambda>  96096 non-null  int64
 20  used_sequential_<lambda>    96096 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(3), object(10)
memory usage: 15.4+ MB

In [40]:
customer_data.columns

Index(['customer_id', 'status_cancel_rate', 'purchase_date_min',
       'customer_city_first', 'customer_state_first', 'customer_zip_first',
       'order_item_id_count', 'price_sum', 'price_mean', 'freight_value_sum',
       'freight_value_mean', 'payment_type_safe_mode',
       'product_weight_g_median', 'seller_id_safe_mode',
       'seller_city_safe_mode', 'seller_state_safe_mode',
       'product_category_safe_mode', 'purchase_time_safe_mode',
       'delivery_days_mean', 'used_installments_<lambda>',
       'used_sequential_<lambda>'],
      dtype='object')

In [43]:
customer_data.rename(columns={"status_cancel_rate":"cancel_rate","purchase_date_min":"first_purchase",'customer_city_first':"customer_city", 'customer_state_first':'customer_state', 'customer_zip_first':'customer_zip',
       'order_item_id_count':'total_orders', 'price_sum':'total_order_price', 'price_mean':'avg_order_price', 'freight_value_sum':'total_freight_value',
       'freight_value_mean':'avg_freight_value', 'payment_type_safe_mode':'fav_payment_mode',
       'product_weight_g_median':'median_product_weight', 'seller_id_safe_mode':'fav_seller_id',
       'seller_city_safe_mode':'seller_city', 'seller_state_safe_mode':'seller_state',
       'product_category_safe_mode':'fav_product_category', 'purchase_time_safe_mode':'fav_purchase_time',
       'delivery_days_mean':'avg_delivery_days', 'used_installments_<lambda>':'payemnt_installments',
       'used_sequential_<lambda>':'sequential_payment'},inplace=True)

In [45]:
pd.set_option("display.max_columns",None)

In [46]:
customer_data.head()

,customer_id,cancel_rate,first_purchase,customer_city,customer_state,customer_zip,total_orders,total_order_price,avg_order_price,total_freight_value,avg_freight_value,fav_payment_mode,median_product_weight,fav_seller_id,seller_city,seller_state,fav_product_category,fav_purchase_time,avg_delivery_days,payemnt_installments,sequential_payment
0,0000366f3b9a7992bf8c76cfdf3221e2,0.0,2018-05-10,cajamar,SP,7787,1,129.90,129.90,12.00,12.00,credit_card,1500.0,da8622b14eb17ae2831f4ac5b9dab84a,piracicaba,SP,bed_bath_table,morning,6.0,1,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,0.0,2018-05-07,osasco,SP,6053,1,18.90,18.90,8.29,8.29,credit_card,375.0,138dbe45fc62f1e244378131a6801526,sao paulo,SP,health_beauty,morning,3.0,0,0
2,0000f46a3911fa3c0805444483337064,0.0,2017-03-10,sao jose,SC,88115,1,69.00,69.00,17.22,17.22,credit_card,1500.0,3d871de0142ce09b7081e2b9d1733cb1,campo limpo paulista,SP,stationery,night,26.0,1,0
3,0000f6ccb0745a6a4b88665a16c9f078,0.0,2017-10-12,belem,PA,66812,1,25.99,25.99,17.63,17.63,credit_card,150.0,ef506c96320abeedfb894c34db06f478,sao paulo,SP,telephony,night,20.0,1,0
4,0004aac84e0df4da2b147fca70cf8255,0.0,2017-11-14,sorocaba,SP,18040,1,180.00,180.00,16.89,16.89,credit_card,6050.0,70a12e78e608ac31179aea7f8422044b,jacarei,SP,telephony,evening,13.0,1,0

In [47]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [50]:
data=data.merge(order_reviews,on='order_id',how='left')

In [54]:
review_scores=data[['customer_id','review_score']].groupby('customer_id')['review_score'].mean().reset_index(name='avg_review_score')

In [56]:
customer_data=customer_data.merge(review_scores,on='customer_id',how='left')

In [57]:
customer_data.head()

,customer_id,cancel_rate,first_purchase,customer_city,customer_state,customer_zip,total_orders,total_order_price,avg_order_price,total_freight_value,avg_freight_value,fav_payment_mode,median_product_weight,fav_seller_id,seller_city,seller_state,fav_product_category,fav_purchase_time,avg_delivery_days,payemnt_installments,sequential_payment,avg_review_score
0,0000366f3b9a7992bf8c76cfdf3221e2,0.0,2018-05-10,cajamar,SP,7787,1,129.90,129.90,12.00,12.00,credit_card,1500.0,da8622b14eb17ae2831f4ac5b9dab84a,piracicaba,SP,bed_bath_table,morning,6.0,1,0,5.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,0.0,2018-05-07,osasco,SP,6053,1,18.90,18.90,8.29,8.29,credit_card,375.0,138dbe45fc62f1e244378131a6801526,sao paulo,SP,health_beauty,morning,3.0,0,0,4.0
2,0000f46a3911fa3c0805444483337064,0.0,2017-03-10,sao jose,SC,88115,1,69.00,69.00,17.22,17.22,credit_card,1500.0,3d871de0142ce09b7081e2b9d1733cb1,campo limpo paulista,SP,stationery,night,26.0,1,0,3.0
3,0000f6ccb0745a6a4b88665a16c9f078,0.0,2017-10-12,belem,PA,66812,1,25.99,25.99,17.63,17.63,credit_card,150.0,ef506c96320abeedfb894c34db06f478,sao paulo,SP,telephony,night,20.0,1,0,4.0
4,0004aac84e0df4da2b147fca70cf8255,0.0,2017-11-14,sorocaba,SP,18040,1,180.00,180.00,16.89,16.89,credit_card,6050.0,70a12e78e608ac31179aea7f8422044b,jacarei,SP,telephony,evening,13.0,1,0,5.0

In [67]:
customer_data.to_csv(r"C:\Users\Rano's PC\Machine\github_repo_cloned\Elevvo_Internship\Task-9\customer_data.csv",index=False)