In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
features=pd.read_csv(r"C:\Users\Rano's PC\Machine\github_repo_cloned\Elevvo_Internship\Task-7\features.csv")
stores=pd.read_csv(r"C:\Users\Rano's PC\Machine\github_repo_cloned\Elevvo_Internship\Task-7\stores.csv")
train=pd.read_csv(r"C:\Users\Rano's PC\Machine\github_repo_cloned\Elevvo_Internship\Task-7\train.csv")
test=pd.read_csv(r"C:\Users\Rano's PC\Machine\github_repo_cloned\Elevvo_Internship\Task-7\test.csv")

In [3]:
train.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [4]:
test.head()

   Store  Dept        Date  IsHoliday
0      1     1  2012-11-02      False
1      1     1  2012-11-09      False
2      1     1  2012-11-16      False
3      1     1  2012-11-23       True
4      1     1  2012-11-30      False

In [5]:
train=train.merge(features,on=['Store','Date'],how='left').merge(stores,on='Store',how='left')

In [6]:
test=test.merge(features,on=['Store','Date'],how='left').merge(stores,on='Store',how='left')

In [7]:
def create_features(df):
    df = df.copy()
    
    # make all columns lowercase
    df.columns = df.columns.str.lower()
    
    # lag features
    df["lag_1"] = df.groupby(["store", "dept"])["weekly_sales"].shift(1)
    df["lag_2"] = df.groupby(["store", "dept"])["weekly_sales"].shift(2)
    df["lag_12"] = df.groupby(["store", "dept"])["weekly_sales"].shift(12)
    
    return df

In [8]:
train.columns = train.columns.str.strip().str.lower()
test.columns  = test.columns.str.strip().str.lower()

In [9]:
train['date'] = pd.to_datetime(train['date'])
test['date']  = pd.to_datetime(test['date'])

In [10]:
for df in (train, test):
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month

In [11]:
train['__set'] = 'train'
test['__set']  = 'test'

In [12]:
train.head()

,store,dept,date,weekly_sales,isholiday_x,temperature,fuel_price,markdown1,markdown2,markdown3,markdown4,markdown5,cpi,unemployment,isholiday_y,type,size,year,month,__set
0,1,1,2010-02-05,24924.50,False,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,A,151315,2010,2,train
1,1,1,2010-02-12,46039.49,True,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True,A,151315,2010,2,train
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False,A,151315,2010,2,train
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False,A,151315,2010,2,train
4,1,1,2010-03-05,21827.90,False,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False,A,151315,2010,3,train

In [13]:
test['weekly_sales'] = np.nan

In [14]:
full = pd.concat([train, test], ignore_index=True)

In [15]:
full.head()

,store,dept,date,weekly_sales,isholiday_x,temperature,fuel_price,markdown1,markdown2,markdown3,markdown4,markdown5,cpi,unemployment,isholiday_y,type,size,year,month,__set
0,1,1,2010-02-05,24924.50,False,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,A,151315,2010,2,train
1,1,1,2010-02-12,46039.49,True,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True,A,151315,2010,2,train
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False,A,151315,2010,2,train
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False,A,151315,2010,2,train
4,1,1,2010-03-05,21827.90,False,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False,A,151315,2010,3,train

In [16]:
full = full.sort_values(['store','dept','date']).reset_index(drop=True)

In [17]:
full['lag_1']  = full.groupby(['store','dept'])['weekly_sales'].shift(1)
full['lag_2']  = full.groupby(['store','dept'])['weekly_sales'].shift(2)
full['lag_52'] = full.groupby(['store','dept'])['weekly_sales'].shift(52)

In [18]:
full.head()

,store,dept,date,weekly_sales,isholiday_x,temperature,fuel_price,markdown1,markdown2,markdown3,...,unemployment,isholiday_y,type,size,year,month,__set,lag_1,lag_2,lag_52
0,1,1,2010-02-05,24924.50,False,42.31,2.572,NaN,NaN,NaN,...,8.106,False,A,151315,2010,2,train,NaN,NaN,NaN
1,1,1,2010-02-12,46039.49,True,38.51,2.548,NaN,NaN,NaN,...,8.106,True,A,151315,2010,2,train,24924.50,NaN,NaN
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,...,8.106,False,A,151315,2010,2,train,46039.49,24924.50,NaN
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,...,8.106,False,A,151315,2010,2,train,41595.55,46039.49,NaN
4,1,1,2010-03-05,21827.90,False,46.50,2.625,NaN,NaN,NaN,...,8.106,False,A,151315,2010,3,train,19403.54,41595.55,NaN

In [19]:
full.columns

Index(['store', 'dept', 'date', 'weekly_sales', 'isholiday_x', 'temperature',
       'fuel_price', 'markdown1', 'markdown2', 'markdown3', 'markdown4',
       'markdown5', 'cpi', 'unemployment', 'isholiday_y', 'type', 'size',
       'year', 'month', '__set', 'lag_1', 'lag_2', 'lag_52'],
      dtype='object')

In [20]:
full.drop(columns=['markdown1', 'markdown2', 'markdown3', 'markdown4','markdown5','isholiday_y',],inplace=True)

In [21]:
full.head()

,store,dept,date,weekly_sales,isholiday_x,temperature,fuel_price,cpi,unemployment,type,size,year,month,__set,lag_1,lag_2,lag_52
0,1,1,2010-02-05,24924.50,False,42.31,2.572,211.096358,8.106,A,151315,2010,2,train,NaN,NaN,NaN
1,1,1,2010-02-12,46039.49,True,38.51,2.548,211.242170,8.106,A,151315,2010,2,train,24924.50,NaN,NaN
2,1,1,2010-02-19,41595.55,False,39.93,2.514,211.289143,8.106,A,151315,2010,2,train,46039.49,24924.50,NaN
3,1,1,2010-02-26,19403.54,False,46.63,2.561,211.319643,8.106,A,151315,2010,2,train,41595.55,46039.49,NaN
4,1,1,2010-03-05,21827.90,False,46.50,2.625,211.350143,8.106,A,151315,2010,3,train,19403.54,41595.55,NaN

In [22]:
full=full.sort_values(by=['store','dept','date'])

In [23]:
full.drop(columns=['lag_2'],inplace=True)

In [24]:
full.head(1)

,store,dept,date,weekly_sales,isholiday_x,temperature,fuel_price,cpi,unemployment,type,size,year,month,__set,lag_1,lag_52
0,1,1,2010-02-05,24924.5,False,42.31,2.572,211.096358,8.106,A,151315,2010,2,train,NaN,NaN

In [25]:
train = full[full['__set']=='train'].drop(columns=['__set'])
test  = full[full['__set']=='test'].drop(columns=['__set','weekly_sales'])

In [26]:
train.head()

,store,dept,date,weekly_sales,isholiday_x,temperature,fuel_price,cpi,unemployment,type,size,year,month,lag_1,lag_52
0,1,1,2010-02-05,24924.50,False,42.31,2.572,211.096358,8.106,A,151315,2010,2,NaN,NaN
1,1,1,2010-02-12,46039.49,True,38.51,2.548,211.242170,8.106,A,151315,2010,2,24924.50,NaN
2,1,1,2010-02-19,41595.55,False,39.93,2.514,211.289143,8.106,A,151315,2010,2,46039.49,NaN
3,1,1,2010-02-26,19403.54,False,46.63,2.561,211.319643,8.106,A,151315,2010,2,41595.55,NaN
4,1,1,2010-03-05,21827.90,False,46.50,2.625,211.350143,8.106,A,151315,2010,3,19403.54,NaN

In [27]:
test.head()

,store,dept,date,isholiday_x,temperature,fuel_price,cpi,unemployment,type,size,year,month,lag_1,lag_52
143,1,1,2012-11-02,False,55.32,3.386,223.462779,6.573,A,151315,2012,11,27390.81,39886.06
144,1,1,2012-11-09,False,61.24,3.314,223.481307,6.573,A,151315,2012,11,NaN,18689.54
145,1,1,2012-11-16,False,52.92,3.252,223.512911,6.573,A,151315,2012,11,NaN,19050.66
146,1,1,2012-11-23,True,56.23,3.211,223.561947,6.573,A,151315,2012,11,NaN,20911.25
147,1,1,2012-11-30,False,52.34,3.207,223.610984,6.573,A,151315,2012,11,NaN,25293.49

In [28]:
train.columns

Index(['store', 'dept', 'date', 'weekly_sales', 'isholiday_x', 'temperature',
       'fuel_price', 'cpi', 'unemployment', 'type', 'size', 'year', 'month',
       'lag_1', 'lag_52'],
      dtype='object')

In [29]:
test.columns

Index(['store', 'dept', 'date', 'isholiday_x', 'temperature', 'fuel_price',
       'cpi', 'unemployment', 'type', 'size', 'year', 'month', 'lag_1',
       'lag_52'],
      dtype='object')

In [30]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 421570 entries, 0 to 536594
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   store         421570 non-null  int64
 1   dept          421570 non-null  int64
 2   date          421570 non-null  datetime64[ns]
 3   weekly_sales  421570 non-null  float64
 4   isholiday_x   421570 non-null  bool
 5   temperature   421570 non-null  float64
 6   fuel_price    421570 non-null  float64
 7   cpi           421570 non-null  float64
 8   unemployment  421570 non-null  float64
 9   type          421570 non-null  object
 10  size          421570 non-null  int64
 11  year          421570 non-null  int32
 12  month         421570 non-null  int32
 13  lag_1         418239 non-null  float64
 14  lag_52        261083 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(7), int32(2), int64(3), object(1)
memory usage: 45.4+ MB

In [31]:
(train.isnull().sum()/len(train)*100).round(2)

store            0.00
dept             0.00
date             0.00
weekly_sales     0.00
isholiday_x      0.00
temperature      0.00
fuel_price       0.00
cpi              0.00
unemployment     0.00
type             0.00
size             0.00
year             0.00
month            0.00
lag_1            0.79
lag_52          38.07
dtype: float64

In [32]:
from xgboost import XGBRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

In [33]:
train=train.dropna(subset=['lag_1']).reset_index(drop=True)

In [34]:
for df in [train, test]:
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month
    df['day'] = df['date'].dt.day  # optional
    df.drop('date', axis=1, inplace=True)

In [35]:
le = LabelEncoder()
train['type'] = le.fit_transform(train['type'])
test['type'] = le.transform(test['type'])

In [36]:
X=train.drop(columns=['weekly_sales'])
y=train['weekly_sales']

In [37]:
tscv = TimeSeriesSplit(n_splits=5)
for train_idx, val_idx in tscv.split(X):
    X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

In [38]:
model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

In [39]:
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [40]:
y_pred = model.predict(X_val)
rmse = np.sqrt(mean_squared_error(y_val, y_pred))
print(f"Validation RMSE: {rmse:.2f}")

Validation RMSE: 3085.00

In [41]:
model.predict(test)

array([34681.24 , 74474.35 , 77787.805, ..., 92223.79 , 90476.59 ,
       92832.016], dtype=float32)